### ISSUE TITLE
Issues with pushing to docker hub

### ISSUE THREAD

**Issue by torrespro** [plexsystems/sinker#10]
Hi there, first of all, great tool!

I'm trying in my local, basic use case, read from a company repo and push to docker.io but I'm getting:

_Error: push: pushing image to target: pushing image after tag: denied: requested access to the resource is denied_

This is the dummy example:

```
target:
  registry: docker.io
  repository: torrespro
images:
- repository: authentication-dev
  version: IPS-1.12.0-no-production
  source: company/docker-releases
```

I can both push and pull from the terminal using plain docker commands, I understood if I can push and pull the client could do it also, or do I need to set up credentials to push to docker.io? if so, how?

Thanks in advance
