### ISSUE TITLE
[Feature] Allow target registries that do not support / in the name

### ISSUE THREAD

**Issue by sudermanjr** [plexsystems/sinker#21]
I would like to be able to sync images from a quay repository to my docker hub account. 

For example, I have this 

```
target:
  repository: fairwindsops
sources:
- repository: coreos/flannel
  host: quay.io
  tag: v0.12.0
```

As it is right now, this tries to push `fairwindsops/coreos/flannel:v0.12.0` which is not valid.  It would be nice to be able to rewrite the repository name somehow. Perhaps `fairwindsops/coreos_flannel:v0.12.0` or something like that.
