### ISSUE TITLE
[Feature] Support update manifest from List type

### ISSUE THREAD

**Issue by sudermanjr** [plexsystems/sinker#23]
For example, I would like to be able to run something like:

```
kubectl deploy,ds,statefulset -A -oyaml > all.yaml
sinker update all.yaml
```

This would enable generating a manifest from all the objects in a cluster. 

The list format is something like this

```
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
```
