### ISSUE TITLE
Panic when spec.container.args uses newlines instead of = sign

### ISSUE THREAD

**Issue by dmegyesi** [plexsystems/sinker#30]
Sinker [expects](https://github.com/plexsystems/sinker/blob/7c6e66e398866b2ebce00acd7142d862396a1b24/internal/manifest/kubernetes.go#L226) the following format when havings `args` with a Docker image in them:
```
    spec:
      serviceAccountName: "argo"
      containers:
        - name: controller
          image: "argoproj/workflow-controller:v2.9.5"
          imagePullPolicy: IfNotPresent
          command: [ "workflow-controller" ]
          args:
          - "--configmap"
          - "release-name-workflow-controller-configmap"
          - "--executor-image=argoproj/argoexec:v2.9.5"
```

and when I have the following in my manifest, it panics:

```
  spec:
      serviceAccountName: "argo"
      containers:
        - name: controller
          image: "argoproj/workflow-controller:v2.9.5"
          imagePullPolicy: IfNotPresent
          command: [ "workflow-controller" ]
          args:
          - "--configmap"
          - "release-name-workflow-controller-configmap"
          - "--executor-image"
          - "argoproj/argoexec:v2.9.5"
```

The cause is the missing `=` sign, as this manifest is using newline characters instead.

```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/plexsystems/sinker/internal/manifest.getImagesFromContainers(0xc0000e8b00, 0x1, 0x4, 0x0, 0x0, 0x0)
	/Users/daniel.megyesi/go/pkg/mod/github.com/plexsystems/sinker@v0.11.2/internal/manifest/kubernetes.go:236 +0x4c2
github.com/plexsystems/sinker/internal/manifest.getImagesFromResource(0xc0003eac37, 0x532, 0x1, 0x1, 0xc00030b5b0, 0x1, 0x1)
	/Users/daniel.megyesi/go/pkg/mod/github.com/plexsystems/sinker@v0.11.2/internal/manifest/kubernetes.go:166 +0x251
github.com/plexsystems/sinker/internal/manifest.GetImagesFromKubernetesResources(0xc00025faf8, 0x1, 0x1, 0x3, 0x0, 0x3744, 0x0, 0x0)
	/Users/daniel.megyesi/go/pkg/mod/github.com/plexsystems/sinker@v0.11.2/internal/manifest/kubernetes.go:45 +0x17b
github.com/plexsystems/sinker/internal/manifest.GetImagesFromStandardInput(0x7ffeefbff943, 0x4, 0x7ffeefbff943, 0x4, 0x4)
	/Users/daniel.megyesi/go/pkg/mod/github.com/plexsystems/sinker@v0.11.2/internal/manifest/manifest.go:276 +0x319
github.com/plexsystems/sinker/internal/commands.runCreateCommand(0x7ffeefbff93e, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/daniel.megyesi/go/pkg/mod/github.com/plexsystems/sinker@v0.11.2/internal/commands/create.go:68 +0x3d6
github.com/plexsystems/sinker/internal/commands.newCreateCommand.func1(0xc000398580, 0xc0003da7e0, 0x1, 0x3, 0x0, 0x0)
	/Users/daniel.megyesi/go/pkg/mod/github.com/plexsystems/sinker@v0.11.2/internal/commands/create.go:38 +0x2f1
github.com/spf13/cobra.(*Command).execute(0xc000398580, 0xc0003da7b0, 0x3, 0x3, 0xc000398580, 0xc0003da7b0)
	/Users/daniel.megyesi/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003982c0, 0x0, 0x0, 0xc0000400b8)
	/Users/daniel.megyesi/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/daniel.megyesi/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/Users/daniel.megyesi/go/pkg/mod/github.com/plexsystems/sinker@v0.11.2/main.go:10 +0x27
```

Having newline separated args (without the `=` sign) is a very common thing in the Kubernetes world, so it could be very nice if this is also supported and parsed correctly.
