### ISSUE TITLE
Allow tags to be overwritten

### ISSUE THREAD

**Issue by jpreese** [plexsystems/sinker#33]
I currently use `lstags` for syncing. It supports all kinds of fancy regexes for defining versions (but of course they come with their own caveats)
Maybe supporting a list of tags for syncing `images` would come handy as well (do not know how to handle digest, though):
```
target:
  host: myhost.com
  repository: my/repo
images:
- repository: library/debian
  host: registry.hub.docker.com
  tag:
   - stretch
   - stretch-slim
   - buster
   - buster-slim
   - testing
   - sid
```

_Originally posted by @mfriedenhagen in https://github.com/plexsystems/sinker/issues/8#issuecomment-686611812_
