### ISSUE TITLE
Feature Request - Support wildcard in tags

### ISSUE THREAD

**Issue by vikas027** [plexsystems/sinker#40]
It would be great to have a wildcard in tags, something like this

```yaml
sources:
- host: 111111111111.dkr.ecr.ap-southeast-2.amazonaws.com
  repository: config-monkey
  tag: dev-*

target:
  host: 222222222222.dkr.ecr.ap-southeast-2.amazonaws.com
```
