### ISSUE TITLE
Feature Request - Support Multiple Targets

### ISSUE THREAD

**Issue by vikas027** [plexsystems/sinker#41]
It would be great to support multiple targets, something like this

```yaml
sources:
- repository: vikas027/alpine
  host: docker.io
  tag: minimal

targets:
- host: 111111111111.dkr.ecr.ap-southeast-2.amazonaws.com
- host: 222222222222.dkr.ecr.ap-southeast-2.amazonaws.com
```
