### ISSUE TITLE
Misidentify images in error logging level parameters

### ISSUE THREAD

**Issue by ssmiller25** [plexsystems/sinker#44]
Mis-identification of container URLs on a specific arguments.  A quick manifest that demos the error is below:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {}
  name: testdeployment
spec:
  selector:
      matchLabels: {}
  template:
    spec:  
      containers:
      - args:
        - --proxyComponentLogLevel=misc:error
        - --log_output_level=default:info
        name: test
        image: busybox
```
