### ISSUE TITLE
Question: odd repos in output from sinker create?

### ISSUE THREAD

**Issue by dewe** [plexsystems/sinker#46]
Question: when using `sinker create`, we're seeing some false image repos in the output manifest...

Given that we have

```yaml
 - args:
    - --secure-listen-address=[$(IP)]:9100
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:10902
```

we get

```yaml
- repository: '[$(IP)]'
  tag: "9100"
- repository: 0.0.0.0
  host: 0.0.0.0:10901
  tag: "10901"
- repository: 0.0.0.0
  host: 0.0.0.0:10902
  tag: "10902"
```

Is there some way to get around this behaviour?

I'm on version 0.14.2.
