### ISSUE TITLE
Add support for a filter cli flag in the sync command

### ISSUE THREAD

**Issue by aslafy-z** [plexsystems/sinker#48]
Allow filtering images to synchronize based on the name of the images.

eg: `images.yaml`
```yaml
sources:
- repository: coreos/prometheus-operator
  host: quay.io
  tag: v0.40.0
- repository: super/secret
  tag: v0.3.0
  auth:
    username: DOCKER_USER_ENV
    password: DOCKER_PASSWORD_ENV
- repository: nginx
  digest: sha256:bbda10abb0b7dc57cfaab5d70ae55bd5aedfa3271686bace9818bba84cd22c29
```

```shell
sinker -m images.yaml push --filter nginx
```
will push only the images matching the filter (as a regexp).
