### ISSUE TITLE
support adding additional tag(s) to the targets

### ISSUE THREAD

**Issue by briantist** [plexsystems/sinker#59]
I want to be able to specify a new tag or tags that will be set (in addition to the existing ones) when syncing.

For example something like this:

```yaml
target:
  host: ghcr.io
  repository: briantist
  additional_tags:
    - stable-2.11
sources:
- repository: ansible/base-test-container
  host: quay.io
  tag: 2.1.0
- repository: ansible/default-test-container
  host: quay.io
  tag: 5.4.0
```

So that the two source images would get synced to the target with both their original tag, and the additional tag(s) entered, like `ansible/base-test-container:2.1.0` would also be `ansible/base-test-container:stable-2.12`.
